name: Release Operator App

on:
  push:
    tags:
      - '*'

permissions:
  contents: write   # needed for attaching files to releases

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Extract version
        shell: bash
        run: |
          VERSION="${GITHUB_REF#refs/tags/v}"
          echo "APP_VERSION=$VERSION" >> $GITHUB_ENV
          echo "PATCH=$(echo $VERSION | cut -d. -f3)" >> $GITHUB_ENV

      - name: Build Windows Desktop
        run: |
          cd OperatorApp
          .\win-publish-release.ps1

      - name: Zip Windows Desktop artifact
        shell: pwsh
        run: |
          cd OperatorApp/Publish
          Compress-Archive `
            -Path * `
            -DestinationPath ../Calibrix-Desktop-Operator-Windows-${{ env.VERSION }}.zip

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            OperatorApp/Calibrix-Desktop-Operator-Windows-${{ env.VERSION }}.zip
